### ISSUE TITLE
ResolveConfigSize doesn't resolve size for Surfaces without a size

### ISSUE THREAD

**Issue by ManuelOverdijk** [IjzerenHein/famous-flex#100]
Hey Hein,

As per commit aa4649e494d9fa6238f4ae2f9d22d322f5079d1e, ```_resolveConfigSize(renderNode)``` returns configSize.size = null for Surfaces without an explicitly defined size. This results in an ```Cannot read property '0' of null``` as configSize.size is not defined. 

For instance, breaking the current NavBarLayout example code:

```javascript
dataSource: {
    background: new Surface({properties: {backgroundColor: 'black'}}),
    title: new Surface({content: 'My title'}),
   ...
```

For anyone encountering the same issue, just a small workaround:
```javascript
dataSource: {
    background: new Surface({properties: {backgroundColor: 'black'}}),
    title: new Surface({content: 'My title', size:[true, true]}),
   ...
```

**Comment by IjzerenHein** [comment]
Ah, thanks for the heads up Manuel!

I'll let you know when this is fixed!

**Comment by IjzerenHein** [comment]
Alright, has been fixed.
Thanks!
