### ISSUE TITLE
minor spelling error in ScrollController.js: touchMoveDirectionThresshold should be written touchMoveDirectionThreshold

### ISSUE THREAD

**Issue by quentinburley** [IjzerenHein/famous-flex#101]
minor spelling error in ScrollController.js: touchMoveDirectionThresshold should be written touchMoveDirectionThreshold

impact also on tutorials/FlexScrollView.md

better to fix this early before many people start using the bad spelling.

**Comment by IjzerenHein** [comment]
Hi, thanks for letting me know! I've renamed the 'threshold' options to use only one s. I've also included a bit of backwards compatibility code so that when the old options are used, it still works but generates a warning.
Thanks.

**Comment by IjzerenHein** [comment]
Hi, I've just released a new version with the new spelling.
For backwards compatibility, I've included the old spelling as well, but when used it will generate a warning and that it will become deprecated in the future.
