### ISSUE TITLE
goToPage with noAnimation: true is good but, in the case of a current index at a close distance to the target index the animation still occurs

### ISSUE THREAD

**Issue by quentinburley** [IjzerenHein/famous-flex#102]
recently a parameter noAnimation was introduced to:
>
FlexScrollView.prototype.goToPage = function(index, noAnimation) {

I have performed some tests with noAnimation: true, with a full screen FlexScrollView containing full screen slides (i.e. everything set to size: [1024x768]). FlexScrollView is set with margin: 1024.

Results: goToPage with noAnimation: true performs as expected ONLY in the case that the target slide is at a distance of >2 slides from the current index.

In the case that the target slide is close to the target slide, i.e. a distance of 1 or 2 slides, the animation still occurs even though noAnimation: true has been set.

Thanks.

**Comment by IjzerenHein** [comment]
Alright, thanks for letting me know. I'll do some tests with test and get back to you.

**Comment by IjzerenHein** [comment]
Hi, a quick question, were you using option "flow: true" on the FlexScrollView? If so, than I'm pretty sure it's fixed now with the commit I just did on master.

**Comment by quentinburley** [comment]
Yes. The FlexScrollView in question was set with "flow: true".
I will re-test on master and share the results.
Thanks

**Comment by quentinburley** [comment]
Re-tested this scenario against master: git://github.com/IjzerenHein/famous-flex.git#661ad26
OK. Looks like it's resolved. Thanks!

**Comment by IjzerenHein** [comment]
Awesome!
