### ISSUE TITLE
Scrollview: scroll without animation

### ISSUE THREAD

**Issue by markmarijnissen** [IjzerenHein/famous-flex#109]
Is there an API call to do this? (Reset to top position without animation)

**Comment by IjzerenHein** [comment]
Yes, all goToxxx functions now have a `noAnimation` argument which you can set to `true`.
I do suggest using the latest master branch, as it includes a fix for that which has not yet been released on npm.

**Comment by IjzerenHein** [comment]
Hey I've just released a new version which fixes the bug I mentioned.
Let me know whether the bug has been resolved.
cheers dude

**Comment by IjzerenHein** [comment]
ping @markmarijnissen
