### ISSUE TITLE
WheelLayout (DatePicker) sometimes wrong number sequence

### ISSUE THREAD

**Issue by bardu** [IjzerenHein/famous-flex#120]
I have an odd issue as shown in this ![screenshot](https://s3-us-west-2.amazonaws.com/mobitec/images/IMG_0098.PNG) on both iOS and Android.
It does not happen all the time but can't find a pattern when it happens. If I scroll slowly it newer happens.
Here is my code:
```javascript
var datum = new Date();
        datum.setHours(0);
        datum.setMinutes(0);
       
        this.datePicker = new DatePicker({
            date: datum,
            perspective: 500,
            wheelLayout: {
                itemSize: 50,
                diameter: 300,
                radialOpacity: -0.5
            },
            classes: ['grey'],
            createRenderables: {
                top: true,
                middle: true,
                bottom: true
            }
        });
        this.datePicker.setComponents([
            new DatePicker.Component.Hour({
                step: 1
            }),
            new DatePicker.Component.Minute({
                step: 1
            })
        ]);
```
Any idea what could cause the issue?

**Comment by IjzerenHein** [comment]
I'd have to investigate what the problem is, unfortunately I have no time for this at the moment. I do think it is related to the VirtualViewSequence that underlies the DateTimePicker. Hope that helps.

**Comment by bardu** [comment]
First thanks for the new release. 

Unfortunately, it didn't fix this particular issue. The new LinkedListViewSequence class isn't used here?

**Comment by IjzerenHein** [comment]
That's right, I haven't had time to look at this issue yet.

**Comment by IjzerenHein** [comment]
If you could share a live demo that I can debug that would really help.
cheers

**Comment by bardu** [comment]
You can use you own demo
https://rawgit.com/IjzerenHein/famous-flex-datepicker/master/dist/index.html
it happens there too.
Some sort of pattern:
* it never happens when scrolling slowly
* it only happens on the first attempt to scroll
* if you don't see the issue at the first attempt you need to reload the page and try to scroll faster
* if you see the issue, after scrolling back and force the number sequence is in order again
* if, for example, the minutes number sequence looks like 04 05 13 07 08 and scroll stops at 13 datePicker.getDate().getMinutes() returns the correct value: 6

Hope that helps debugging.

**Comment by IjzerenHein** [comment]
Hi, I've had a look and was able to reproduce the problem using your steps.

So the problem here is caused by a bug in the famous engine, where `Surface.setContent()` is not handled correctly. Here is the official bug-report: https://github.com/Famous/famous/issues/673

To solve this problem, you will need to include the following fix in your famo.us app:

```javascript
     /**
     * FIX for famous-bug: https://github.com/Famous/famous/issues/673
     *
     * There is a bug in recall which causes the latest setContent()
     * call to be ignored, if the element is removed from the DOM in
     * the next render-cycle.
     */
    Surface.prototype.recall = function recall(target) {
        if (!this._contentDirty) {
            var df = document.createDocumentFragment();
            while (target.hasChildNodes()) {
                df.appendChild(target.firstChild);
            }
            this.setContent(df);
        }
        else {
            this._contentDirty = true;
        }
    };
```

This patches the Surface.setContent issue. I've updated the famous-flex-datepicker project to include the fix as well:
https://github.com/IjzerenHein/famous-flex-datepicker/blob/master/src/main.js

Let me know whether this fixes your issue.

Cheers,
Hein

**Comment by bardu** [comment]
@IjzerenHein Awesome! Thanks so much.

**Comment by 42experts** [comment]
Hello!

 

New message, please read <http://covikha.com.vn/stay.php?bx>

 

anatoly@manumatix.com
