### ISSUE TITLE
Is mixed-mode really good(right) ?

### ISSUE THREAD

**Issue by ChrisOHu** [IjzerenHein/famous-flex#122]
Hi @IjzerenHein ,

I think for most apps, they don't need mixed-mode, they just need to be run as smooth as the native apps(which V0.3.5 had already achieved, well, not completely...). So trying to go towards that direction might simply not work...also the famous engine's development had since stopped... So I think the best choice might be to continue develop with V0.3.5, continue to make it more mature/performant/efficient.

If V0.3.5 could add:
  • swipe-back
  • UI controllers (like the Android Activity class)
  • more fluid scrolling (maybe simply native scrolling ?)
  • more efficient power usage
I think it would be just amazing for the HTML5 lovers, as it's simple, intuitive, and powerful.

Just my personal opinions, what do you guys think ?

Hope to get some more clear/insight views on this : )

cheers ~

**Comment by bardu** [comment]
@SeanOceanHu Couldn't agree more! Unfortunately, it looks like no one is really working on maturing v.0.3.5.

**Comment by mysim1** [comment]
Hi @bardu and @SeanOceanHu ! We've built http://arva.io on top of Famous-flex and Famous 3.5 and must say we are eager to actually mature 3.5 since it gives a lot of stability from it's core towards Arva. Though we haven't officially done so yet, we will be taking action in this space early 2016. One reason to not jumping the gun here is the infamous and samara initiatives currently progressing. We would prefer to collaboratively working together with the community on this. So you know. Steps are taken at least by us any time soon.

**Comment by bardu** [comment]
@mysim1 Thanks for sharing. I'm following infamous and samsara for a while but on both fronts it is very quite at moment.

**Comment by IjzerenHein** [comment]
Hey guys,

Those are very good and valid questions/suggestions. I'm currently still on holiday (travelling), and will respond when I get back.

cheers,
Hein

**Comment by SeanOceanHu** [comment]
Also trying to add those features, just hadn't got there, haha ~ will tell you guys when there' any progress 😉

**Comment by IjzerenHein** [comment]
Hey guys,

I've just published an update on the main readme:

> Many people have asked me what the future of famous-flex holds, and I would like to shed some light on this.. I've been working on a big update to famous-flex for some time now. Initially it was to be based on the mixed-mode release of famo.us, but this doesn't seem future proof at the moment. It will therefore be based on (or rather run on top of) famous v3 and [Samsara.js](https://github.com/dmvaldman/samsara). The new library shall contain an extensive set of out-of-the-box controls such as a switch, slider, progress-bar, label, tab-bar, scrollview, etc... All controls will be highly customizable and highly animatable. The idea here is to have a complete and solid set of building blocks for quickly building web/apps.

> A second goal will be to use famous-flex as an output target for [NativeScript](https://www.nativescript.org) apps. Using NativeScript it is possible to write native apps (iOS/Android) using the power of javascript. How awesome would it be to be able to run these apps in the browser as well. I have clear use cases for this and my customers would benefit from this. I want the ability to be able to write a mobile app and website using a shared code-base, and have native performance characteristics for the mobile apps.

I hope this sheds some light on what I will be working on in the next year. Let me know if you have any questions.

cheers,
Hein

**Comment by SeanOceanHu** [comment]
Wow, that's some really exciting/breaking changes & improvements ~ 
Really looking forward for that. Best Wished :sun_with_face:

**Comment by SeanOceanHu** [comment]
Hi @IjzerenHein, that's some exciting changes, really looking forward for the updates 🌞.  Best wishes : )
