### ISSUE TITLE
Surface leakage issue because of Entity.register

### ISSUE THREAD

**Issue by SeanOceanHu** [IjzerenHein/famous-flex#124]
Hi guys,
please checkout this issue on stackoverflow: http://stackoverflow.com/questions/23623586/how-to-remove-surfaces-from-a-layout?lq=1

Wondering if this also exists in famous-flex ?

PS. Happy new year :beers:

**Comment by IjzerenHein** [comment]
Famous-flex itself doesn't have such a leak. It doesn't keep track of surfaces or anything in global lookup dictionaries. Famous v3 does so you have to be a bit careful with it. I myself never always create as little surfaces/views as possible and re-use surfaces/views where possible. For instance by putting them in a pool when not needed anymore and re-using those when needed (e.g. for dynamically populated lists).

Does that answer your question?

**Comment by SeanOceanHu** [comment]
Hi @IjzerenHein ,
Thanks~
