### ISSUE TITLE
Error: 

### ISSUE THREAD

**Issue by atgillette** [IjzerenHein/famous-flex#128]
I'm using npm version of this library and I'm getting the following error:

`ReferenceError: Can't find variable: assert`
`insertLinkedListViewSequence.js:88`

It looks like the assert function is not included in the distribution code.

**Comment by atgillette** [comment]
I also noticed that going from version 0.3.2 to 0.3.7 causes this error and now I cant get FlexScrollView to  accept surfaces, no matter how I try to add surfaces.

**Comment by atgillette** [comment]
Looks like the introduction of LinkedListViewSequence in version 0.3.6 broke FlexScrollView.

**Comment by bardu** [comment]
@atgillette LinkedListViewSequence didn't break anything for me in FlexScrollView.

**Comment by atgillette** [comment]
Hi @bardu,

I did not make any code changes when switch from 0.3.2 to 0.3.7 and all of a sudden it stop working with the error on the insert method in LinkedListViewSequence.

There's something with the introduction of LinkedListViewSequence that's not quite right.  I even swapped out the node module for version 0.3.5, which is prior to LinkedListViewSequence, and that works.

**Comment by IjzerenHein** [comment]
Hi, the `LinkedListViewSequence` class was apparently missing from the global dist file. Also, the `assert` function was defined outside the AMD scope so I think that caused the `missing assert` issue. Both have been addressed in the v0.3.9 version which has just been released.
Let me know whether it works correctly now.
cheers

**Comment by atgillette** [comment]
Everything seems to be working now.  Thx
