### ISSUE TITLE
Something really odd is happening with the scrolling

### ISSUE THREAD

**Issue by StephanBijzitter** [IjzerenHein/famous-flex#22]
* Desktop: no issue
* iOS: ???
* Android (4.4): scrolling is smooth if the finger used to scroll started on the image, but is not smooth if you start scrolling without your finger anywhere else.

Source:  https://github.com/StephanBijzitter/Famous-Material-Examples
I also patched Scrollview.js with this PR (but it doesn't seem to change anything for this demo): https://github.com/talgleichger/famous/commit/6740e1da838d90dea6dfec0ff3e34e0673dd706a

I really don't understand what's going on and how this is happening, it makes no sense :'(

**Comment by IjzerenHein** [comment]
Ping @StephanBijzitter

**Comment by StephanBijzitter** [comment]
Resolved on above issue
