### ISSUE TITLE
FlexScrollview cannot render true width surfaces correctly.

### ISSUE THREAD

**Issue by adamelk** [IjzerenHein/famous-flex#36]
I am having trouble rendering surfaces with height and width set to [true,true] in the FlexScrollview.  Basically, the width is getting confined to some max-width, even when I explicitly set a max-width that is larger.  This is important because I am building a chat where the chat bubbles need to have a [true,true] size and a max-width that I specify.  The image attached shows the behavior that is exhibited.  The second image shows the same chatbubble code added to the DOM but not in the FlexScrollview.
![screen shot 2014-12-28 at 12 18 23 am](https://cloud.githubusercontent.com/assets/3347307/5572391/ba00c418-8f6b-11e4-80d4-2479c81edec4.png)

![screen shot 2014-12-26 at 9 20 48 pm](https://cloud.githubusercontent.com/assets/3347307/5572414/063bbcf2-8f6c-11e4-9476-89118efa280d.png)

**Comment by IjzerenHein** [comment]
Hi, could you share the surface/view code of your chat-bubbles so I can have a look at it?

**Comment by adamelk** [comment]
How I organized my messenger was with ChatBubble views that have an ImageSurface for a picture and an ExtendedSurface for the actual message.  The ExtendedSurface allows me to get the height of the true surface and set the views size to that height, so the scrollview can render the View.  My problem is that for some reason, it confines the true width of the surface to some max-width, which isn't the max-width that I set.  You can ignore the stuff that says "document" and "this.options...", these are just data from Meteor I use to populate the views.    

    // a modified surface to emit an event after setting the real height and width for true sized surfaces
     define("ExtendedSurface",function(require, exports, module) {
     var Surface = require('famous/core/Surface');

    function ExtendedSurface(){
        Surface.apply(this, arguments);
        this._superDeploy = Surface.prototype.deploy;
    }

    ExtendedSurface.prototype = Object.create(Surface.prototype);
    ExtendedSurface.prototype.constructor = ExtendedSurface;
    
    ExtendedSurface.prototype.deploy = function deploy(target) {
        this._superDeploy(target);
         var size = this.getSize();
          this.setSize([this._currentTarget.clientWidth,this._currentTarget.clientHeight])
          this.realHeight = this._currentTarget.clientHeight
          this.realWidth = this._currentTarget.clientWidth
          this._eventOutput.emit("isDeployed");
    }

    module.exports = ExtendedSurface;
    });


    //chat bubble view
    function ChatBubble(){
      View.apply(this,arguments);
    
      var chat = this;
      var origin; 
      var align; 
      var backgroundColor;

      var renderNode = new RenderNode({
        size: [undefined, 0.1*heightScreen]
      });

      if(this.options.user){
        content = '<div style="max-width:'+ widthScreen*0.6 + 'px; margin-right: 10px; margin-left: 10px;       margin-bottom: 10px; margin-top: 10px; color: #fff; font-family: Open Sans, sans-serif; font-size:'+ heightScreen / 40 +'px;">'+ this.options.message +'</div>';
        origin = [1.0,0.5];
        align = [0.95, 0.5];
        backgroundColor = "#66ccff";
      }
      else{
        content = '<div style="max-width:'+ widthScreen*0.6 + 'px; margin-right: 10px; margin-left: 10px; margin-bottom: 10px; margin-top: 10px; color: #000; font-family: Open Sans, sans-serif; font-size:'+ heightScreen / 40 +'px;">'+ this.options.message + '</div>'
        origin = [0,0.5];
        align = [0.2, 0.5];
        backgroundColor = "#f0f0f0";
        picture = new ImageSurface({
          content: this.options.picture,
          size: [0.075*heightScreen, 0.075*heightScreen],
          properties: {
            borderRadius: "50%"
          }
        });
        pictureMod = new Modifier({
          origin: [0.5,0.5],
          align: [0.1, 0.8]
        });

        this.add(pictureMod).add(picture);
      }

      // problem is here where I set the size to [true,true], extended surface emits an event output after deployed and i grab the real height and width
      this.bubble = new ExtendedSurface({
        size: [true, true],
        content: content,
        properties: {
          backgroundColor : backgroundColor,
          borderRadius: "15px"
        }
      });
      var bubbleMod = new Modifier({
        origin: origin,
        align: align
      });


      this.bubble.on('isDeployed', function(){
          chat.setOptions({size : [undefined, chat.bubble.realHeight]});
      });

      this.add(bubbleMod).add(this.bubble);
      this.add(renderNode);
    }


    // this is where I add the ChatBubble view to the scrollView

    var bubble = new ChatBubble({size: [undefined, true], user: user, picture: Meteor.user().picture,   message: document.message, timeSent: document.timeSent});
    bubble.bubble.pipe(scrollView);
    scrollView.push(bubble, {opacity: 0});

**Comment by IjzerenHein** [comment]
Hi, thanks for all the info.

I have investigated the problem and found that the problem lies in the Group component of famo.us and not specifically in famous-flex. The problem also occurs when you add your Bubble-view to a stock famo.us Scrollview (which uses the same optimized group-scrolling as the flex-scrollview).
It seems that the browser calculates the height/width differently when the div has a parent div with a width and height of 0px. Which is what famo.us inserts into the DOM when you use a Group.

Here is the relevant famo.us code (famous/core/Group.js):
```javascript
/**
     * Apply changes from this component to the corresponding document element.
     *
     * @private
     * @method commit
     *
     * @param {Object} context update spec passed in from above in the render tree.
     */
    Group.prototype.commit = function commit(context) {
        var transform = context.transform;
        var origin = context.origin;
        var opacity = context.opacity;
        var size = context.size;
        var result = Surface.prototype.commit.call(this, {
            allocator: context.allocator,
            transform: Transform.thenMove(transform, [-origin[0] * size[0], -origin[1] * size[1], 0]),
            opacity: opacity,
            origin: origin,
            //size: Group.SIZE_ZERO // this causes the problem
            size: context.size // this fixes it
        });
        if (size[0] !== this._groupSize[0] || size[1] !== this._groupSize[1]) {
            this._groupSize[0] = size[0];
            this._groupSize[1] = size[1];
            this.context.setSize(size);
        }
        this.context.update({
            transform: Transform.translate(-origin[0] * size[0], -origin[1] * size[1], 0),
            origin: origin,
            size: size
        });
        return result;
    };
```

Now perhaps this can be fixed through (hacky) workarounds, but I'd rather not go down that route. I would suggest submitting it to famo.us with a clearly defined test-case. And otherwise I would revise your solution and try to solve it differently. Also note that there is no such thing as 'true-sized' views. True-size only applies to Surfaces. The surface creates a div and then the DOM calculates the width/height for the surface. A view does not correspond to anything in the DOM.

**Comment by adamelk** [comment]
Thank you for your help.  I will submit this issue to Famo.us.

**Comment by IjzerenHein** [comment]
@adamelk please close this issue if you feel it was answered. Cheers!

**Comment by StephanBijzitter** [comment]
You could also opt for a monospace font and calculate the needed width and height beforehand.
Say each character is 10 pixels and you want a bubble to be at least 100 pixels wide, but no wider than 300, there'd be 30 characters max per line. Given a message of 96 characters you'd set the width to 300+spacing and the height to Math.ceil(96/30)*lineHeight+spacing.
