### ISSUE TITLE
Adding a ListLayout as child of a ListLayout

### ISSUE THREAD

**Issue by christianvoigt** [IjzerenHein/famous-flex#37]
Hi, I tried to put a ListLayout within a ListLayout (I want to use a RenderController to show/hide a sub-list). Is this possible? So far I haven't succeeded. Here is a minimal example:

```javascript
define(function(require, exports, module) {
    'use strict';

var Engine = require('famous/core/Engine');
var Surface = require('famous/core/Surface');
var LayoutController = require('famous-flex/LayoutController');
var ListLayout = require('famous-flex/layouts/ListLayout');

var mainContext = Engine.createContext();

var layoutController1 = new LayoutController({
    layout: ListLayout,
    flow: true,    
    direction: 1,  
    dataSource: [
        new Surface({content:"surface 1",size:[undefined,30]}),
        new Surface({content:"surface 2",size:[undefined,30]}),
        new Surface({content:"surface 3",size:[undefined,30]})
    ]
});     

var layoutController2 = new LayoutController({
    layout:ListLayout,
    flow:true,
    direction:1,
    dataSource: [
        new Surface({content:'the beginning',size:[undefined,30]}),
        layoutController1,
        new Surface({content:'the end',size:[undefined,30]})
    ]
});
mainContext.add(layoutController2);
});
```

The "the end" surface is not shown below "surface 3". Have I done something wrong, or is this a bug?

**Comment by IjzerenHein** [comment]
I like the idea of letting the LayoutController use the size of the child renderables. I'll see whether I can come up with an elegant solution for it.

**Comment by IjzerenHein** [comment]
Hi, I've implemented this feature. I've added the ability to specify `size: [undefined, true]` to a LayoutController. It will then calculate the height of all the child renderables, which is then returned by the `layoutController.getSize` function.

Example:
```javascript
var layoutController = new LayoutController({
   layout: ListLayout,
   size: [undefined, true], // tell the LayoutController to derive the height from the child-renderables
   dataSource: [
      new Surface({
         size: [undefined, true],
         content: 'sample text'
      }),
      new Surface({
         size: [undefined, true],
         content: 'sample text<br><br>testing'
      })
    ]
});
```

I've created a demo project for it here:
https://github.com/IjzerenHein/famous-flex-truesize-layoutcontroller-demo

Let me know whether this solves your problem.
Cheers!

**Comment by christianvoigt** [comment]
This solved my problem. Thank you for your great work and a happy new year!

**Comment by IjzerenHein** [comment]
Awesome, great to hear!
Happy new year to you too.
