### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by jchonde** [IjzerenHein/famous-flex#38]
Hello, 
Congratulation for your work, it will be very useful to the famo.us community ! 
I would like to use it in a commercial project and I don't see any licence.
Do you have any informations about this ?

Thank you !

**Comment by IjzerenHein** [comment]
Hi!
It uses the MIT license, so it's free to use for everyone (there is a file called LICENSE in the root of the repo).
Cheers!

**Comment by jchonde** [comment]
My bad :) thank you !
