### ISSUE TITLE
CollectionLayout justify is not working

### ISSUE THREAD

**Issue by StephanBijzitter** [IjzerenHein/famous-flex#41]
![http://puu.sh/esoVL.png](http://puu.sh/esoVL.png)
I'm trying to get my buttons in the horizontal center using `[true, false]`, but regardless of what values I give, it doesn't do anything.

Note that this is on all browsers, and my android device.
I don't know if any recent update broke this or not, it's my first time using it.

**Comment by IjzerenHein** [comment]
@StephanBijzitterl the `justify` option is part of the CollectionLayout, so you have to specify it inside `layoutOptions`.

**Comment by StephanBijzitter** [comment]
Heh... okay. Yep, got it, derp.
