### ISSUE TITLE
LayoutOptions cannot be changed using `setOptions` function

### ISSUE THREAD

**Issue by StephanBijzitter** [IjzerenHein/famous-flex#42]
When an event occurs, I want to be able to change the layout options, but I seem to be unable to do so.
Calling `FlexScrollView.setOptions({layoutOptions:{something:a}})` results in nothing being rendered, at all.

Right now I just want to change the itemSize in a CollectionLayout

**Comment by IjzerenHein** [comment]
Hmm that's weird, that should work.
Could you share the code that you are using?
What event are you responding to?
There is also a function called `setLayoutOptions` which you can use, but using `setOptions` with property `layoutOptions` should also work.

**Comment by StephanBijzitter** [comment]
https://github.com/Skelware/Fancy-Flashlight/commit/6295216cd84639a8a1e068fde162c4061b40b7ec

**Comment by IjzerenHein** [comment]
Alright thanks, I'll go look into it.

**Comment by IjzerenHein** [comment]
Fixed
