### ISSUE TITLE
RenderNodes in dataSource instead of surfaces.

### ISSUE THREAD

**Issue by vplifer** [IjzerenHein/famous-flex#43]
Hello IjzerenHein, and thank you for such great scrollview, it's really awesome!

But I have one little trouble. 

I need to create listLayout from items.
Each item has 4 surfaces.

So each item is RenderNode.

Scrollview takes data from array, that contains all RenderNodes.

The problem is that scrollview in this case is not scrolling. 

Here is some code:
```javascript
var nodeSequence = new ViewSequence();

for(i = 0; i < 40; i++) {
	var surfaceOne = new Surface({
		size: [undefined, 50],
		content: 'one',
		properties: {
			backgroundColor: '#888'
		}
	});
	var surfaceTwo = new Surface({
		size: [undefined, 50],
		content: 'two',
		properties: {
			backgroundColor: '#222'
		}
	});
	var node = new RenderNode();
	node.add(surfaceOne).add(surfaceTwo);
	nodeSequence.push(node);
}

var myScroll = new ScrollController({
	layout: ListLayout,
	layoutOptions: {
		itemSize: 100
	},
	dataSource: nodeSequence,
	autoPipeEvents: true,
	mouseMove: true,
	debug: true
});

// I bult layout from modifiers, so layout node is from there.
layoutNode.add(myScroll);
```

It all works if _nodeSequence_ contains surfaces.

**So what I do wrong?**
Is there a way to make list item that contains many surfaces?

Thank's.

PS
With default famous Scrollview it also doesn't work.

**Comment by IjzerenHein** [comment]
Hi!

You cannot add Surfaces to Surfaces in famo.us. What exactly are you trying to achieve with this line:
```javascript
node.add(surfaceOne).add(surfaceTwo);
```

Are you trying to create a div inside a div or something like that?

cheers

**Comment by vplifer** [comment]
Thank's for quick feedback.

Okay, but it doesn't work even with:

```
node.add(surfaceOne);
```

No, I need to create list of items that has draggable surfaces in it.
And have ability to animate each surface in item separately.

**Comment by IjzerenHein** [comment]
I think you should do it like this:

```javascript
var node = new RenderNode(surfaceOne);
nodeSequence.push(node);
```

**Comment by vplifer** [comment]
Already tried, and now tried again - same result.

**Comment by IjzerenHein** [comment]
Ah now I understand.

RenderNode does not have an event-handler, so the `autoPipeEvents` options cannot do its magic.

You need to pipe the events from the Surfaces into the ScrollController like this:

```javascript
surfaceOne.pipe(myScroll);
```

Typically, you create a View and put all your surfaces in there, and pipe the events from the Surfaces to the View. And since View does have an event-handler, `autoPipeEvents` will work.

**Comment by vplifer** [comment]
Yes! It worked. Thank you so much, I spent more then 10 hours trying to figure out what's wrong...

But it works with `surfaceOne.pipe(myScroll);` only. `autoPipeEvents` doesn't work even with View.

**Comment by IjzerenHein** [comment]
Yes it will work with Views, I am sure of that. Inside the view, you have to pipe the events from the Surfaces to the views this._eventOutput, like this:

```javascript
function MyView(options) {
  View.apply(this, arguments);
  
  var surface = new Surface({..});
  this.add(surface);
  surface.pipe(this._eventOutput);
}
MyView.prototype = Object.create(View.prototype);
MyView.prototype.constructor = MyView;
```

**Comment by vplifer** [comment]
Okay, I don't know why, but it works only if I do pipe to `view._eventOutput`:

```javascript
var view = new View();
view._add(surfaceOne);
view._add(surfaceTwo);

nodeSequence.push(view);

surfaceOne.pipe(view._eventOutput);
surfaceTwo.pipe(view._eventOutput);
```

More than likely I do something wrong. But it really works with this additional pipes.

So `autoPipeEvents` works with view, thank's again.
