### ISSUE TITLE
Is there a way to use Famous Flex with Meteor Views?

### ISSUE THREAD

**Issue by vplifer** [IjzerenHein/famous-flex#44]
Hello.

Is there a way to do something like this?
```Haskell
{{#ScrollController id="surfaceListScroll"}}
    {{#Surface}}SurfaceOne{{/Surface}}
    {{#Surface}}SurfaceTwo{{/Surface}}
    {{#Surface}}SurfaceThree{{/Surface}}
{{/ScrollController}}
```
Of course already did this:
```javascript
FView.registerView('ScrollController', famous.flex.ScrollController);
```

It works good with default `Scrollview`. 

**The main question:**
Is it possible to have `dataSource` property of `ScrollController` pointing on child elements in Render Tree?

**Comment by vplifer** [comment]
I found that you can do this: 
```Haskell
{{#ScrollController id="surfaceListScroll"}}
    {{#SequentialLayout id="surfaceListSequence"}}
        {{#Surface}}SurfaceOne{{/Surface}}
        {{#Surface}}SurfaceTwo{{/Surface}}
        {{#Surface}}SurfaceThree{{/Surface}}
    {{#/SequentialLayout}}
{{/ScrollController}}
``` 

And then, in JavaScript do this:
```javascript
var surfaceListScroll = FView.byId("surfaceListScroll").view;
var surfaceListSequence = FView.byId("surfaceListSequence").view._items;

surfaceListScroll.setOptions({
	layout: ListLayout,
	layoutOptions: {
		itemSize: 100
	},
	dataSource: surfaceListSequence,
	autoPipeEvents: true
});
```

It will display all content from this `{{#SequentialLayout}}`, but it will not scroll.
I think it's mean that any of this surfaces have not been piped to `ScrollController`.

Maybe because `SequentialLayout` has not `._eventOutput`?

**Comment by IjzerenHein** [comment]
Hi, I've yet to work with Meteor famous Views myself (it's on my todo list).
I suggest posting this question in the meteor-famous-views repo, or on this item:
https://github.com/gadicc/meteor-famous-views/issues/178

**Comment by vplifer** [comment]
Okay, thank's. Missed this issue...

**Comment by IjzerenHein** [comment]
Hi, please post the solution here if possible. Thanks!

**Comment by gadicc** [comment]
Yeah, there are a lot of us famous-views folk who are very eager to integrate famous-flex in famous-views.  We were talking about it last year but then holidays kicked in.  I think mcbain might have already started, and I'm also keen to give this a bash as soon as I finish catching up on other stuff.  I don't think getting a single view of the flex working would be too hard, but we want to keep the "flex" and that will require a little more work... I think it's going to be awesome when it's done though, and will be a pleasure to use reactive data stores :)  Watch for updates in the issue IjzerenHein linked to.

@IjzerenHein, did you ever check out https://fview-lab.meteor.com/pads/qXd9Zm6bPm8NiuZeX

**Comment by IjzerenHein** [comment]
@gadicc Cool :) I'll hopefully get into it soon :)

Btw, I'm working on new widgets build upon famous-flex. Have you seen the new date-timer widget?
https://github.com/IjzerenHein/famous-flex/blob/master/tutorials/DatePicker.md
More will follow soon.

**Comment by thomasfl** [comment]
@IjzerenHein The datePicker is awesome. Looks great on iOS.

https://rawgit.com/IjzerenHein/famous-flex-datepicker/master/dist/index.html

**Comment by gadicc** [comment]
I second the awesome comment!  Super cool.  Hope to have all this stuff integrated in famous-views soonish.  One line datepicker with reactive data from the database will be awesome :>

`{{>datePicker time=createdAt}}`

**Comment by IjzerenHein** [comment]
Yay :))))

**Comment by gadicc** [comment]
Hope everyone's following on the [famous-views thread](https://github.com/gadicc/meteor-famous-views/issues/178)... I just announced an early attempt in https://github.com/gadicc/meteor-famous-views/issues/178#issuecomment-73072352.
