### ISSUE TITLE
Combined & minified js

### ISSUE THREAD

**Issue by peacechen** [IjzerenHein/famous-flex#47]
What's the recommended way to combine & minify the famous-flex source?  When I require('famous-flex/FlexScrollView'), for example, the browser pulls 10 separate famous-flex files.

If there's interest and you (Hein) would like help with this, I can try my hand at writing a grunt build to create a single minified file.

Another advantage of a single source file is that it would be much easier to create live demos on jsfiddle, etc.

**Comment by thomasfl** [comment]
Have you seen how webpack is used in https://github.com/IjzerenHein/famous-flex-chat?

    npm install -g grunt
    npm install -g webpack

It packs all used js and css into one file. Webpack also seems to have better amd support than browserify.

**Comment by mcbain** [comment]
Recently i made a first attempt with browsify (which currently does not work anymore).

     npm run-script global-no-famous

A better solution is also welcome.

**Comment by IjzerenHein** [comment]
Yes I use webpack for all my web-projects these days. The big benefit is that it merges all files into a single bundle which can be loaded very fast. 

https://github.com/petehunt/webpack-howto

**Comment by mcbain** [comment]
@IjzerenHein will webpack bundle include the famous-core?

**Comment by IjzerenHein** [comment]
@mcbain Yes

**Comment by IjzerenHein** [comment]
With webpack, you basically specify an entry point (your main.js) and webpack then tracks all dependencies and pulls in all required javascript code into a single bundle.

**Comment by IjzerenHein** [comment]
I just fixed the `npm run-script global-no-famous` script.

@mcbain, can I use this require-path `require('famous-flex/LayoutController')` when I use the 'famous-no-template.js' file?

**Comment by mcbain** [comment]
@IjzerenHein imho you need to use relative path e.g. '../LayoutController'

**Comment by IjzerenHein** [comment]
@mcbain In my own code you mean? Yes I know, I made the mistake several times and accidentally used absolute paths instead of relative. I fixed them and famous-flex now uses relative paths for all its own files. I will add 'npm run-script global-no-famous' to my grunt scripts and then it should check for any of those mistakes automatically.

What I was referring to was if another projects wants to use the famous-flex library. How can I use a class from famous-flex using famous-no-global.js?
I would like to distribute a global file similar to: http://code.famo.us/famous/0.3.4/famous.min.js
which then allows someone use famous-flex in this fashion:

```javascript
var ScrollController = require('famous-flex/ScrollController');
```

**Comment by mcbain** [comment]
@IjzerenHein the 'global-no-famous' uses the 'global-no-famous.template'  which export the flex-classes to the global object 'ijzerenhein'.

**Comment by IjzerenHein** [comment]
@mcbain I see, I actually thought so that it would do such a thing. Is this the preferred method for including libraries in meteor?

**Comment by mcbain** [comment]
There is another way using raix:famono - https://github.com/raix/Meteor-famono. 
It's a more generic but also more "heavyweight" solution, than just including one js file.

**Comment by IjzerenHein** [comment]
Hi guys, here is an update to this topic.
As of the next release, famous-flex shall always distribute an up-to-date global version in 'dist/famous-flex-global.js'.

The namespace has been renamed to 'famousflex' (who can spell ijzerenhein correctly anyway... :))
Also, '.layout' has been renamed to '.layouts'.

Let me know what you think of these changes. I don't use the global version myself so I'm relying on you guys for feedback.

cheers,
Hein

**Comment by matt-d-rat** [comment]
@IjzerenHein Sounds good. Can you ensure it is compatible with browserify so it can be consumed in projects which use this as part of their build.

**Comment by IjzerenHein** [comment]
@matt-d-rat I'd love to do that. I don't have much experience with browserify myself, so if someone could test whether the current code in master can be used with browserify that would be awesome.

**Comment by matt-d-rat** [comment]
@IjzerenHein I gave it a test against what was in master and I was getting console errors complaining that famous was undefined, which was very strange. 

I was using it on a test project created using https://github.com/thaiat/generator-angular-famous-ionic.

I normally declare Famous as a separate require dependency which may be why it was having issues. Tried without declaring Famous to no avail.

**Comment by IjzerenHein** [comment]
@matt-d-rat Alright, thanks for trying. 
I don't have much time in the upcoming week to investigate this. The global-famous.js file is generated through this script:
```
browserify ./dist/famous-flex-global.template.js -t browserify-shim -o ./dist/famous-flex-global.js --debug --verbose
```
and the package.json has this shim configured:
```json
"browserify-shim": {
    "famous/core/OptionsManager": "global:famous.core.OptionsManager",
    "famous/utilities/Utility": "global:famous.utilities.Utility",
    "famous/surfaces/ContainerSurface": "global:famous.surfaces.ContainerSurface",
    "famous/core/EventHandler": "global:famous.core.EventHandler",
    "famous/core/Transform": "global:famous.core.Transform",
    "famous/core/View": "global:famous.core.View",
    "famous/core/Surface": "global:famous.core.Surface",
    "famous/math/Vector": "global:famous.math.Vector",
    "famous/core/Group": "global:famous.core.Group",
    "famous/physics/PhysicsEngine": "global:famous.physics.PhysicsEngine",
    "famous/physics/forces/Drag": "global:famous.physics.forces.Drag",
    "famous/physics/forces/Spring": "global:famous.physics.forces.Spring",
    "famous/inputs/ScrollSync": "global:famous.inputs.ScrollSync",
    "famous/physics/bodies/Particle": "global:famous.physics.bodies.Particle",
    "famous/transitions/Transitionable": "global:famous.transitions.Transitionable",
    "famous/core/Entity": "global:famous.core.Entity",
    "famous/core/ViewSequence": "global:famous.core.ViewSequence"
  }
```

Perhaps this sheds some light on the situation?

**Comment by dingdreher** [comment]
this works fine, but famous has its directories messed up, what they fix with [famousify](https://github.com/FamousTools/famousify/blob/master/index.js#L26)

**Comment by IjzerenHein** [comment]
@dingdreher Thanks for the heads up!

So in order to use browserify, you need to use famousify as well, is that it?
In the new 0.3.5 release famo.us changed the paths, and it no longer has the 'src' location.
Would this mean famousify is no longer needed for browserify users?

**Comment by IjzerenHein** [comment]
I've just released a new version v0.2.0 on NPM and bower. It includes all the public contributions in this area. Let me know whether this solves the problems or not? Cheers

**Comment by mutazmq** [comment]
@IjzerenHein 
The library looks great but I have not been able to use it. Tried webpack and browserify with no success.
Can you please provide us with instructions on how to use it? Or a template project?
I have been trying for the last three days and don't know what else I should try.
Thanks

**Comment by mutazmq** [comment]
I also ran (webpack) command successfully, but when I run

    grunt serve 

in [famous-flex-chat](https://github.com/IjzerenHein/famous-flex-chat), but the command halts with errors that I'm not able to figure out how to fix them.

**Comment by cj3kim** [comment]
@mutazmq 

I have successfully used famous–flex with browserify together. You need to delete all lines that contain the require function and it will be browserifiable (because you have converted from require to commonjs format).

**Comment by IjzerenHein** [comment]
@mutazmq, I just noticed there was small error in instruction in the famous-flex-chat project. 'grunt-cli' and not 'grunt' should have been installed globally. Does that fix your problem? If not just post the errors that you are getting here or in a new issue in the famous-flex-chat project.

Alternatively, you can use my Starterkit for famo.us, it contains famous-flex by default:
https://github.com/IjzerenHein/famous-Starterkit

**Comment by mutazmq** [comment]
@cj3kim 
I tried it but didn't work because unintentionally I kept the script tags for require and famous. I removed them now and it works. Thanks

**Comment by mutazmq** [comment]
@IjzerenHein 
I get http://paste.ofcode.org/38Qg7SqZrGAWU6nUNbkxS4U when I execute this in famous-flex-chat

    grunt serve

Yes, grant-cli is global and grunt local but still got the above error. I tried your Starterkit and it builds and runs well. Thanks

**Comment by IjzerenHein** [comment]
Hi, the latest version of famous-flex (v0.3.2), contains all new generated /dist files to meet different kind of integration scenarios. It contains the following files:
- dist/famous-flex-global.js
- dist/famous-flex-global.min.js
- dist/famous-flex.js
- dist/famous-flex.min.js

I've also created a test project, which showcases how to integrate famous-flex using different technologies (requirejs, global, wepback, browserify:
https://github.com/IjzerenHein/famous-lib-tester

**Comment by peacechen** [comment]
Thanks Hein, this is great!

**Comment by mutazmq** [comment]
@IjzerenHein Thanks a bunch!
