### ISSUE TITLE
offset of a FlexScrollView element

### ISSUE THREAD

**Issue by Qvatra** [IjzerenHein/famous-flex#48]
How to get offset of an element that is inside FlexScrollView?

**Comment by Qvatra** [comment]
I did figure out that I can do it by asking it in matrices:

        var offset_x = flexScrollView._dataSource[id]._matrix[12];
        var offset_y = flexScrollView._dataSource[id]._matrix[13];

which is work but I also need to know the flexScrollView Offset. 
For some reason flexScrollView.getOffset() doesn't show absolute offset of a view. I don't know what it shows.. maybe offset from the last scroll...

How to get absolute offset?

**Comment by IjzerenHein** [comment]
Yikes!

If you want to offset a renderable, I suggest you wrap it inside Modifier, and give the Modifier a translation offset:

```javascript
var RenderNode = require('famous/core/RenderNode');
var Surface = require('famous/core/Surface');
var Modifier = require('famous/core/Modifier');
var Transform = require('famous/core/Transform');

// Create a surface that is offsetted 10px down
var mod = new Modifier({
  transform: Transform.translate(0, 10, 0)
});
var sur = new Surface({..});
var node = new RenderNode(mod);
node.add(sur);

// Add surface to scrollview
scrollView.push(node);
```


To answer your other question. You can use the `getSpec` function to get the absolute position of a renderable. This only works though if the renderable is in the DOM.

**Comment by IjzerenHein** [comment]
Btw, this method:

```javascript
var offset_x = flexScrollView._dataSource[id]._matrix[12];
var offset_y = flexScrollView._dataSource[id]._matrix[13];
```

Don't use it. You are accessing private members of the FlexScrollView and Surface. These will possibly change in a future update causing your code to break.

**Comment by Qvatra** [comment]
Goedendag, 
here is example of what I want to build: https://dl.dropboxusercontent.com/u/49691996/FamousDemo/kit/examples/views/flexScrollCenter/example.html

onclick event should move red surface to the upper left corner independently of the position of the scroll.
I'm use here private members:
               var offset_x = flexScrollView._dataSource[3]._matrix[12];
		var offset_y = flexScrollView._dataSource[3]._matrix[13];
		var absoluteScrollPosition = flexScrollView._scroll.groupStart + flexScrollView.getOffset();

I really don't know how to get these values in a right way.... Can you help me?

1) I can't use getSpec because my red surface doesn't have it.
2) In documentation is said that  flexScrollView.getOffset() is the scroll position of the flexscrollview but I've found out that its not absolute - if you have a lot of elements offset resets continuously while scrolling (after each reset scroll.groupStart collects that value so I've found a way to get absolute position)
3) Is it possible to disable scrolling after onclick event?

**Comment by Qvatra** [comment]
OK I was stupid to search getSpec in surface. it's a function of a flexScrollView. One question less
