### ISSUE TITLE
Animate item height in FlexScrollView

### ISSUE THREAD

**Issue by motiazu** [IjzerenHein/famous-flex#53]
Hi,
I'm using FlexScrollView to display a list of items, I need the selected item (a state that my code is handling) to expand it's height.

I tried putting a StateModifier for my item's surfaces (all wrapped with a RenderNode), and animating it. It did work for the animation itself (although im only changing height via scale transform which stretches the content...), but the margin between other items does not change and they intersect. I also tried calling reflowLayout on the scrollview, it didn't seem to help (which makes sense since the item height isn't changing via transform).

So my question boils down to this:
1. Is there a way for FlexScrollView to work good for item height animation?
2. Is there a way to make a Surface taller without stretching it's content (aka not using transform to animate height)?

Thanks.

**Comment by motiazu** [comment]
Solved it by using setSize animation instead of setTransform. For some reason my eyes insisted that the docs don't say anything about animating size.

**Comment by IjzerenHein** [comment]
Awesome, glad to hear you already found the solution!
