### ISSUE TITLE
Option to stop scrolling at the ends without temporary springy edge gap

### ISSUE THREAD

**Issue by peacechen** [IjzerenHein/famous-flex#54]
As originally discussed in [this thread](https://github.com/IjzerenHein/famous-flex/issues/52), sometimes it would be better for the ends of the scrollview to stop at the edge instead of pulling away from it.  The latter looks like how the "pull to refresh" works, where you can pull the list away from the edge and introduce a temporary gap before it snaps back.  What I'd like to see is an option to not allow it to separate from the container edge (no temporary gap).

Please vote for this if you'd like this option too.

**Comment by IjzerenHein** [comment]
Wow, one other person also requested this today, there must definitely be a demand for this.

I've just added the ability to disable overscroll on ScrollController/FlexScrollView. You can disable it like this:

```javascript
var scrollView = new FlexScrollView({
   overscroll: false
});
```

The code has been committed on the master branch. Please have a look at it and let me know whether this meets your requirements.

**Comment by IjzerenHein** [comment]
Duplicate #55

**Comment by peacechen** [comment]
Perfect!  Many thanks for adding this option.
