### ISSUE TITLE
Option to Disable Bounce/Overscroll

### ISSUE THREAD

**Issue by jordangarside** [IjzerenHein/famous-flex#55]
Is there any option to disable bounce/overscroll?

I can't seem to find it anywhere.

**Comment by IjzerenHein** [comment]
Someone else requested that feature yesterday. I've just added it to the master branch.
You can disable it like this:

var scrollView = new FlexScrollView({
   overscroll: false
});

Please let me know whether this meets your requirements, so it can be published in the next release.

**Comment by jordangarside** [comment]
Works perfectly,
Thanks!

**Comment by IjzerenHein** [comment]
Awesome. :+1:
