### ISSUE TITLE
scrollend not emitted from FlexScrollView when alwaysLayout is true

### ISSUE THREAD

**Issue by motiazu** [IjzerenHein/famous-flex#58]
Hi,
I'm have been going nuts over the fact that `scrollend` is not being emitted. After debugging ScrollController for a while I resorted to trying weird things, and the moment I set autoLayout to false in my FlexScrollView's options, the event was being emitted again.

I tried turning it off and on and it certainly the factor that toggles this bug. Thing is, my app relies on both of these things working together :)
I tried looking into the calculations in ScrollController and my brain melted, so I'm just going to leave this as a bug report since I don't know how to fix this.

Thanks.

**Comment by IjzerenHein** [comment]
Hi, great find!
I've just fixed the problem, it will be included in the upcoming release.
Cheers

**Comment by motiazu** [comment]
Great! Thanks, I'll check it out as soon as I can.

2015-02-07 16:21 GMT+02:00 Hein Rutjes <notifications@github.com>:

**Comment by motiazu** [comment]
Works great, thanks for the fix :)
