### ISSUE TITLE
CollectionLayout `direction` value reversed?

### ISSUE THREAD

**Issue by gadicc** [IjzerenHein/famous-flex#61]
Ok, it's only my 3rd day with famous-flex so hope I'm not doing anything stupid :)  But the `direction` (which I'm applying directly to `FlexScrollView` and not via `layoutOptions`) seems to have the opposite behaviour I'd expect - but only for `CollectionLayout`.

It's a bit harder to tell in the famous-flex demo, where you only see the icon and not the current direction, but if you look at http://fview-flex.meteor.com/ where we map direction via `Utilities.Direction[key]`, with `direction="X"` it lays out the renderables vertically, and with `direction="Y"` it does so horizontally, which seems counter-intuitive.

I did just realize that in this case the `direction` does actually represent the way the *scrollview* will scroll, and maybe that was your intention.  It's a bit confusing though.  If you cycle through all the different layouts, all the items are ordered "intuitively" except for this one.  Thoughts?

**Comment by IjzerenHein** [comment]
Hi gadicc! Your last paragraph is spot on. The direction indeed indicates the scrolling direction. This is the way it is intended to work. CollectionLayout basically is a scrollable grid-layout. It first lays out renderables on the same row/column and only when it reaches the end of that row/column does it move on to the next row/column. It may seem strange when you look at it from a perspective of only a few renderables, but when you add hundreds of renderables, the direction will (I think) start to make sense.

**Comment by gadicc** [comment]
Yeah, it does make sense (as I realized even while writing the issue), but it's not obvious at first.  If I'm to be completely honest, for the first two days I was working on it I thought it was a bug, and only realized what was going on while writing up the issue.  It's just because it's the only layout that gets "affected" like this, and it's the opposite of what one would expect (at least initially).  The only thing I'd suggest is clarification in the docs, and the PR above does just that :)

**Comment by IjzerenHein** [comment]
Instead of closing this, I would love to hear has others feel and think about this. I myself didn't have any ambiguous feelings about the way direction is interpreted until you mentioned it. If it really is counter-intuitive than we should change it. The CollectionLayout is inspired strongly after the UICollectionView from UIKit, in which you also set the scrolling-direction.

I'd love to hear others thoughts on this as well.

**Comment by gadicc** [comment]
From my side it was clear to me (and I'm inclined to agree) once it was put in context; the direction option, is, after all, passed to the ScrollView and not the LayoutController.  But definitely would be good to hear what others think.

It's a bit easier to demonstrate the intuitiveness issue on http://fview-flex.meteor.com/ (where the items are numbered).  Switch beween GridLayout and CollectionLayout and you'll see what I mean... the former flows in the specified `direction`, while the latter flows opposite.

**Comment by IjzerenHein** [comment]
Awesome, thanks for the clarification Gadi!
