### ISSUE TITLE
FlexScrollView expand items from center issue

### ISSUE THREAD

**Issue by motiazu** [IjzerenHein/famous-flex#63]
Hi,
My app manages a state for items in FlexScrollView that causes an item to expand it's height.
This works fine just by putting RenderNodes with a StateModifier before the surface itself, and animating it's size.

UX people requested that I would make the item expand it's height from the center (bottom and top) instead of only from one edge. I tried using origin [0, 0.5] and the tranistion itself is done right, but it totally messes up the spacing between the items.

Online example: https://dl.dropboxusercontent.com/u/27964192/famous/index.html
This example just expands the items sequentially (reload to watch again).
Example without origin [0, 0.5], which is how the app is right now.  https://dl.dropboxusercontent.com/u/27964192/famous/index2.html

Thanks.

**Comment by IjzerenHein** [comment]
Hi, I can't load the online examples, it gives this error:

> index.html:9 Mixed Content: The page at 'https://dl.dropboxusercontent.com/u/27964192/famous/index.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://code.famo.us/famous/0.3/famous.css'. This request has been blocked; the content must be served over HTTPS.

**Comment by motiazu** [comment]
If you are running with chrome, you can see a button near the favorite icon in the url field. Press it to load insecure content. This basically happens because dropbox is running via https and im loading famo.us css from http.
![image](https://cloud.githubusercontent.com/assets/8556495/6124180/e40f24e2-b113-11e4-8f93-ccfec63deab0.png)

**Comment by IjzerenHein** [comment]
Ah thanks. I'll investigate when I have some time for it. Cheers

**Comment by IjzerenHein** [comment]
Hi, I see I never really followed up on this. Sorry about that. Is this still an issue you need me to look at?

**Comment by motiazu** [comment]
Probably still an issue, but my company decided to discontinue it's use of famo.us, so it's not relevant for me anymore :(
Performance is still not good enough for vanilla android webview in 4.4

**Comment by IjzerenHein** [comment]
Ok, that's too bad to hear.
Well in that case I'll close this for now, if anyone has this request it can always be reopened.
