### ISSUE TITLE
Distribution minified build + browserify support

### ISSUE THREAD

**Issue by matt-d-rat** [IjzerenHein/famous-flex#65]
I am having an issue with using your awesome library with an application which uses browserify as part of its build.

I originally raised this issue with the yeoman generator I am using: https://github.com/thaiat/generator-angular-famous-ionic/issues/126

But the problem appears to be more on the famous-flex library side in that it doesn't have a minified distribution build as part of the release that is compatible with browserify.

Would you be able to support this please?

**Comment by matt-d-rat** [comment]
Possibly related to https://github.com/IjzerenHein/famous-flex/issues/47 - any guidance you can provide to helping me to get this to work with the aforementioned browserfiy application would be most appreciated.

**Comment by IjzerenHein** [comment]
Yes, please have a look at #47. I just posted a message there with some new information on this.
Cheers

**Comment by IjzerenHein** [comment]
Hi, I just released a new version v0.2.0. I've updated the NPM and bower packages.
Does this solve your problem?

**Comment by matt-d-rat** [comment]
@IjzerenHein thanks for the update. I'll give it a test in the next couple of days and report back to you.

**Comment by IjzerenHein** [comment]
Hi, I've just released a new version of famous-flex (v0.3.2). It contains all new generated /dist files to meet different kind of integration scenarios.
I've also created a test project, which showcases how to integrate famous-flex using different technologies (requirejs, global, wepback, browserify:
https://github.com/IjzerenHein/famous-lib-tester
