### ISSUE TITLE
Clear Viewsequence Error on FlexScrollView.

### ISSUE THREAD

**Issue by trobbertze** [IjzerenHein/famous-flex#66]
Hi

This is a little bit complex to reproduce. But here goes.

If you have a long sequence of lets say 30 items.  Scroll down to the very bottom.

Now execute an event that will clear the sequence and replace it with a much shorter sequence, lets say 10 items.

The 10 new items are not rendered within view and it is impossible to scroll to those items.

**Comment by IjzerenHein** [comment]
Hi Theo.
What layout are you using? And are you using alignment 1?
Cheers

**Comment by trobbertze** [comment]
Im using the standard FlexScrollview.

The only options that I set is:
direction: 1,
 scrollDrag: 10,
 flow: true

**Comment by IjzerenHein** [comment]
What are the functions you are calling to clear the sequence?

**Comment by trobbertze** [comment]
At first I used just a normal array as a sequence and then spliced it.

I then tried using a proper ViewSequence and did

sequence.splice(0, sequence._.array.length)

But that had the same effect.

Seems as if the sequence cannot find the first node once it is cleared like
that.

**Comment by IjzerenHein** [comment]
The ViewSequence is not the best invention of famo.us imho... When you clear the view-sequence in that way, the ScrollView will still hold a reference to one of the removed view-sequence nodes. There is no proper way for the scrollview to detect that the view-sequence was cleared out.
The FlexScrollView contains a function called 'removeAll' which should always properly clear the  content, please use that function.

**Comment by trobbertze** [comment]
Thanks Hein

Worked like a charm!

Only thing to note is that you have to set the datasource again afterwards.

Cheers

Theo

**Comment by IjzerenHein** [comment]
Awesome :+1: 

Please close the issue if you feel it was answered satisfactory.
