### ISSUE TITLE
Request: Dependency Injection

### ISSUE THREAD

**Issue by aintnorest** [IjzerenHein/famous-flex#67]
Sorry If this was already mentioned / asked. So background, I love what you and your contributors have done and wish you were on the famous core team. I've avoided pulling your library in because of it's size. I don't need most it and I already use famous, postal, and  lodash, so my file size is already larger than I'd like. I've been having trouble with the famous scrollview and being able to pull and push items in and out. After seeing the issues about that earlier this week and realizing how easy it is in your library i decided to bite the bullet and import your library.

I use my own forked version of famous that just incorporates some of the pull requests that famous core hasn't pulled in yet. As a product of that any library that requires famous i have to add a /src/ everywhere they require something from famous. When I just added FlexScrollView it pulled in a lot of other files.

I haven't taken the time to look through your code base extensively but feel you could with smaller modules and dependency injection have a smaller code base for those that don't need every feature. This isn't a criticism love everything you've got going on here just trying to be conscious of file size.

**Comment by IjzerenHein** [comment]
Hi @aintnorest,

I solved the problem of large file-sizes by using webpack. Webpack uses dependency-scanning to include only those files that are actually used, into a single bundle. This has the added benefit that only one javascript file has to be loaded from the server, increasing your load times. The bundle itself also doesn't need async/requirejs anymore, making it more performant.
Webpack is really awesome and I strongly recommend it to anyone going into production environments. You can find a famous/webpack starterkit project here: https://github.com/IjzerenHein/famous-Starterkit

**Comment by IjzerenHein** [comment]
ping @aintnorest

**Comment by aintnorest** [comment]
Sorry I supposed you'd just close it... So I use webpack, side thought I love it. Webpack will include anything you require because it can't tell if your using it or not if your importing it. I use a funky version of famous that just has some fixs in it. It has famous/src/...restOfPath so I had to augment yours to point to the augmented pathing that my famous uses. So when I just included the flex scrollview and it made me change the pathing on like 6 other files the thought ran through my head that the library was highly coupled and with some dependency injection you could decouple the library a little so that people not trying to use every feature don't need to pull so much in. It's not a big deal.
