### ISSUE TITLE
why LayoutController.setLayoutOptions() behave as async function?

### ISSUE THREAD

**Issue by Qvatra** [IjzerenHein/famous-flex#73]
I have the following LayoutController:
```
		    var layoutContent = new LayoutController({
				layout: CollectionLayout,
				layoutOptions: {
                itemSize: initSize,
					justify: true,
					margins: [0, 0],
					spacing: gutters
				},
				dataSource: data
			});
```
 in my screenResizeFunction I want to set optimalSize for items:
```
			layoutContent.setLayoutOptions({
				itemSize: optimalSize,
			});
```
and calculate new offset of the specific item-item:
```
			var itemSpec = layoutContent.getSpec(item, false);
			var dx = itemSpec.transform[12];
			var dy = itemSpec.transform[13];
```
the problem is that if I have ~50 items (which are 'heavy' views itself) I receive wrong values of dx and dy; 
The solution is the following:
```
			layoutContent.setLayoutOptions({
				itemSize: optimalSize,
			});
            setTimeout(function(){
                 var itemSpec = layoutContent.getSpec(item, false);
                 var dx = itemSpec.transform[12];
                 var dy = itemSpec.transform[13];
            }, 1000);
```
which means that layoutContent.setLayoutOptions() is async.

what is the right way to change itemSize option of collectionLayout in LayoutController to be sure that LayoutController.getSpec() return already changed transform values?

**Comment by IjzerenHein** [comment]
Hi...

That is correct, all layouting is done async. This is true for all famo.us views, not just a LayoutController. The layouting is done in the next executed render-cycle. What you could do is to wait to the 'layoutend' event. When that has executed, you can safely use 'getSpec' to get the new specs.

```javascript
layoutContent.on('layoutend', function() {
  // get spec here
});
```

**Comment by Qvatra** [comment]
many thanks Hein!

Is it documented somewhere? I mean events of LayoutController.

**Comment by IjzerenHein** [comment]
More or less, in this file:
https://github.com/IjzerenHein/famous-flex/blob/master/docs/LayoutController.md

I still need to write up a proper tutorial for LayoutController, which describes these kinds of aspects.

**Comment by Qvatra** [comment]
ok. thx
