### ISSUE TITLE
FlexScrollView scroll event wrong offset

### ISSUE THREAD

**Issue by motiazu** [IjzerenHein/famous-flex#74]
Hi,
I think I encountered a bug with the scroll event.
It looks like `scrollOffset` is relative to the first visible item, instead of the whole list.

Take a look at this example (make sure you enable loading unsafe scripts to view the example)
https://dl.dropboxusercontent.com/u/27964192/scrollbug/index.html
(link to js https://dl.dropboxusercontent.com/u/27964192/scrollbug/src/main.js )

I have a floating surface above the `FlexScrollView` that translates on Y axis according to the scroll offset.
Once you scroll over the first item, the floating surface goes back to it's initial position, and debugging showed me `scrollOffset` is going back to `0` when this happens.

Another weird behavior in this - if you scroll with your mouse and keep it pressed while scrolling, the `scrollOffset` is staying normal until you leave the mouse, even if you go past items.

This issue basically prevents me from syncing anything with the scroll, unlike `ScrollView` which has a `sync` field that I can bind to.

**Comment by IjzerenHein** [comment]
Hi!
That's correct, `scrollOffset` is indeed relative to the first visible item. This is how it is intended to work, and it very similar how the stock famo.us Scrollview works. This behaviour is by design and makes it possible for the FlexScrollView to handle infinite lists. You should not use `scrollOffset`, because it is not practical and meaningful for you. 
As an alternative, would it be useful if I add like a `delta` value to the scroll and scrollend events so you can use that to sync?

**Comment by motiazu** [comment]
Very interesting, I was wondering if that is done by design for virtualization...
A `delta` value won't help in my case since what I'm really trying to achieve is have the synced element stop syncing when offset is below 10, to create some sort of a "sticky" fixed surface when it is in a certain point.

The only solution I can think of on my side is to calculate the total heights and spaces of items that come before the item in `getFirstVisibleItem`. That sounds like something I would like the framework to do, especially since I'm not sure how this will affect my rendering, since it will be done for every frame.

Any other ideas?

**Comment by neonaleon** [comment]
Hi, I was also trying to do some synchronisation across views, specifically something like a TabbedScrollView (demo here http://theresa.meteor.com), where the active tab indicator would follow the FlexScrollViews' scroll offset. I had trouble using `scrollOffset` as well, and had to use some `getSpec()` computation as suggested in #48 , which feels a little hackish :stuck_out_tongue:
@motiazu: I don't know if this snippet can spark some ideas but here...
```
var pageIndex = scrollview.view.getCurrentIndex();
// scrollview.container is the ContainerSurface holding the FlexScrollView
var scrollviewState = pageIndex * scrollview.container.getSize()[0];
// scrollview.view is the FlexScrollView instance
var scrollviewTranslate = scrollviewState - Transform.interpret(scrollview.view.getSpec(scrollview.view.getFirstVisibleItem().renderNode).transform).translate[0];
```
A `delta` or absolute offset or current scroll position would be helpful I think! But I'm unsure of the implications of dealing with infinite lists when it comes to absolutes :disappointed:

**Comment by motiazu** [comment]
Hmmm this is pretty problematic.
My items are not the same height. I tried using `getFirstVisibleItem` and `getCurrentIndex` to determine from which item the `scrollOffset` is calculated, but none of these changed in sync with the `scrollOffset`.

More specifically, the mentioned methods changed the index before(!) the relevant item became invisible. So basically, I can't find any anchor to when `scrollOffset` is being calculated differently to make my code compensate for the missing scroll data.
Actually, `scrollOffset` is really changing when the top item becomes invisible, unless I keep the mouse pressed which causes it to change the offset anchor only when I release it.

I think adding `delta` could help me in this case, because right now it seems impossible.
The only hack I can think of is to determine when `scrollOffset` had change so radically that it probably skipped an item, but that's a horrible unmaintainable method that won't always work.

**Comment by IjzerenHein** [comment]
Hi! I've given it a bit more thought and I think I've come up with a solution. I've added a new function .getAbsolutePosition to the FlexScrollView, which returns the absolute scroll position from the moment the scrollview started scrolling. This method is also provided for compatibility with the stock famo.us ScrollView.

Additionally, I've changed the meaning of the 'scrollOffset' argument in the `scroll` and `layout` events. The `scrollOffset` now contains the absolute scroll-position. This will work perfectly if you start scrolling from the top. I've committed the change to the master (FlexScrollView.js & ScrollController.js).
Let me know whether this solves the problem for you.

**Comment by motiazu** [comment]
Works great! Totally solved it with `scrollOffset`.

I would mention that now `scrollOffset` is above zero for some reason, so I'm multiplying it by -1 (which I didn't have to before, because it was a negative number).
Was this done on purpose?

**Comment by IjzerenHein** [comment]
Awesome, great to hear!

Yes I made the value positive purposely. I figured it makes more sense that when you scroll the view 10 pixels down, that the absolute scroll position would also be +10. This value is reflected in the `scrollOffset` property for the events as well. This is similar to how the stock famo.us Scrollview does it.

**Comment by motiazu** [comment]
In that case, case closed :)

**Comment by IjzerenHein** [comment]
Woohoo :)
