### ISSUE TITLE
When scrolling embedded FlexScrollView, parent FlexScrollView would also scroll (leadingScrollView & trailingScrollView doesn't seems to work)

### ISSUE THREAD

**Issue by BodhiHu** [IjzerenHein/famous-flex#76]
Hi @IjzerenHein , I have a FlexScrollView like this:

```
var mainScrollView = new FlexScrollView({
  autoPipeEvents: true,
});
var childScrollView_1 = new FlexScrollView({
  autoPipeEvents: true,
  layout: CollectionLayout,
  leadingScrollView: mainScrollView,
  trailingScrollView: mainScrollView,
  useContainer: true,
  container: {
      size: [undefined, height],
      properties: {overflow: 'hidden'}
    }
});
var childScrollView_2 = new FlexScrollView({
  autoPipeEvents: true,
  layout: ListLayout,
  leadingScrollView: mainScrollView,
  trailingScrollView: mainScrollView,
  useContainer: true,
  container: {
      size: [undefined, height],
      properties: {overflow: 'hidden'}
    }
});
var surface1 = new Surface({size: [undefined, 20]});
var surface2 = new Surface({size: [undefined, 20]});
var surface3 = new Surface({size: [undefined, 20]});

mainScrollView.push(surface1);
mainScrollView.push(childScrollView_1, undefined, false);
mainScrollView.push(surface2);
mainScrollView.push(childScrollView_2, undefined, false);
mainScrollView.push(surface3);

mainContext.add(mainScrollView);
```

Now the problem is that, when I scroll the embedded childScrollView_1 or childScrollView_2, mainScrollView would also scroll, even before reaching the top RenderNode (if scrolling up) or bottom RenderNode (if scrolling down) of the child scroll view. As a consequence, if I scrolled pretty deep in child scroll view, I wouldn't be able to go back to the original RenderNode of that child scroll view.

I had read the documentations really carefully, and felt I had set the correct options, also I tried to change different options, but still did not help. So can you give any hints on this ? Any possible details that I had missed that caused this ?

Would really appreciate your help :)
Thanks~

**Comment by ManuelOverdijk** [comment]
+1, I have the same problem here.

**Comment by ShawnOceanHu** [comment]
Hi  @IjzerenHein @ManuelOverdijk ,
I tried to fix this issue, you can see my commit here: https://github.com/ShawnOceanHu/famous-flex/commit/def463458abd09f72df15eb8e73f0b648a5688b4

But that doesn't work.

**Comment by IjzerenHein** [comment]
Hi, I'm sorry I have not had time to look at this properly, it's just too busy at the moment.
