### ISSUE TITLE
Sticky headers documentation typo

### ISSUE THREAD

**Issue by jfizz** [IjzerenHein/famous-flex#77]
Just wanted to make you aware of the typo at https://github.com/IjzerenHein/famous-flex/blob/master/tutorials/FlexScrollView.md#sticky-headers-listlayout which states that the sticky header callback is `isHeaderCallback` when it is actually called `isSectionCallback`. Thanks for your work!

**Comment by IjzerenHein** [comment]
Ah thanks for pointing that out. I've just fixed it.
Thanks!
