### ISSUE TITLE
Thoughts on scroll into view when on a mobile device when keyboard pops up.

### ISSUE THREAD

**Issue by aintnorest** [IjzerenHein/famous-flex#79]
I'm using scrollView.ensureVisible(renderable); to make sure an input is in view on an IOS app. The form works great until the last few items where the scrollview's natural scroll length wouldn't let the input be visible over the top of the ios keyboard. Any thought on how to fix the problem?

As an aside I'm using the following setup for the scrollview:

{
        autoPipeEvents: true,
        useContainer: true,
        container:{
            size:[undefined,Sizing._h - ((Sizing._h * 0.0881)+Sizing.headerH)]
        },
        flow: true,
        layout: ListLayout,
        layoutOptions: {
            margins: [0, mrgn, 0, mrgn],
            spacing: mrgn,
          },
    }

Also I don't seem to be able to scroll the view when the mouse or touch is over the spacing. Works great in your demo but on mine it's like it's not syncing the spacing. Thanks for any help.

**Comment by IjzerenHein** [comment]
Is it possible for you to share a live demo of the problem online, so I can have a closer look and debug it?

Ah, yes for the spacers. Please disable 'autoPipeEvents'. You're also using a container, which automatically captures all events (also at the places where there are no surfaces) and pipes these to the FlexScrollView. Enabling 'autoPipeEvents' currently disables that behavior as events should never be piped twice. I'll try to implement a better solution for this in the next version.

**Comment by IjzerenHein** [comment]
Ping @aintnorest
