### ISSUE TITLE
FastClick issue with "famous-Starterkit"

### ISSUE THREAD

**Issue by mutazmq** [IjzerenHein/famous-flex#80]
Using FastClick:
When I run my project in "famous-Starterkit", which uses Webpack, the "click" event handler fires twice. One for MouseEvent and the other for CustomEvent 

However, when I remove AMD define from famous-flex and use Browserify, I don't get the same problem and click event handler fires once on CustomEvent object .

Has anyone experienced the same issue?

Thanks
Mutaz

**Comment by IjzerenHein** [comment]
Hi, I'm unable to reproduce this with the Starterkit. I installed a click-handler on a surface, and it's only firing once. Could you dump the callstack for both click events here?

**Comment by mutazmq** [comment]
Hi, here we go: http://paste.ofcode.org/hbFDbSGX7hAkFgKEsjdHrL
http://paste.ofcode.org/vhGDP9HE5cwh7VEamTWa5T

I solved it by using ftlabs FastClick instead of Famo.us's one

**Comment by IjzerenHein** [comment]
I'm not sure what I'm supposed to do with that paste of code..

Yes that's right, the famo.us FastClick implementation doesn't work correctly, that's why the famous-Starterkit uses the ftlabs version as well.

**Comment by mutazmq** [comment]
BTW, this issue comes only when I use Webpack. Using Browserify, I can use famous FastClick without any trouble

**Comment by IjzerenHein** [comment]
My hunch is that the Browserify version actually breaks an event-chain, making it accidentally work.
