### ISSUE TITLE
LayoutController transition option

### ISSUE THREAD

**Issue by Qvatra** [IjzerenHein/famous-flex#82]
I would like to set a transition for resizing of LayoutController.
According to the documentation I should set 
```
{
flow: true,
reflowOnResize: true
}
```
but how i should specify the actual transition? for example: 
```
transition = { curve: 'easeOut', duration: 1000 }
```

**Comment by IjzerenHein** [comment]
The flow-mode uses physics particles & springs, and thus you cannot use transitions. Instead you can set the options for the node-springs, like this:

```javascript
var layoutController = new LayoutController({
  flow: true,
  nodeSpring: {
    dampingRatio: 0.8,
    period: 1000
  }
});
```

**Comment by Qvatra** [comment]
ok. thx. 
Is it documented somewhere?
I didn't find "nodeSpring" option in LayoutController doc.

**Comment by IjzerenHein** [comment]
Hi, it was indeed not documented in LayoutController, but in ScrollController. I've added it to the source of LayoutController and the docs will be automatically updated when the next version is released.
Thanks.

**Comment by IjzerenHein** [comment]
Hi, just a note on this. I'm just about to release famous-flex v0.3.0. In this version, `nodeSpring` has been renamed to `flowOptions.spring`.
