### ISSUE TITLE
on 'layoutend' event fires before nodes were set.

### ISSUE THREAD

**Issue by Qvatra** [IjzerenHein/famous-flex#83]
Hello, 

I've noticed that after on 'layoutend' event was fired I still don't have access to nodes specs via getSpec() function - it's undefined, but with setTimeout wrapper it works:
```
  var layoutController = new LayoutController({
    layout: ListLayout,
    layoutOptions: {
       itemSize: 50
    },
    dataSource: surfArray
  });

  layoutController.on('layoutend', function(){
   // setTimeout(function(){  // <----------------setTimeout solves this issue
    	console.log('layoutend ' + layoutController.getSpec(surfArray[0], false).size);
   // }, 500);
  });
```

Here is codePen proof (see log): 

http://codepen.io/Qvatra/pen/EarRxJ

P.S: I've tested on Chrome only.

is it a bug? what is a workaround?

**Comment by IjzerenHein** [comment]
Hi, thanks for reporting this. I've just checked in the fix for this, let me know whether that solves your problem.
Cheers

**Comment by Qvatra** [comment]
thx. bug is gone
