### ISSUE TITLE
FlexScrollView laggy on Android device

### ISSUE THREAD

**Issue by ShawnOceanHu** [IjzerenHein/famous-flex#84]
Hi @IjzerenHein ,
I found FlexScrollView is bit laggy on the Android device(try to repeatedly scroll with your finger very quickly), though the scrolling is really smooth on my iPad  and Macbook. I suppose the scrolling algorithm is the same regardless of devices, on the other hand, the famo.us animations are actually really smooth on my Nexus 4, so I'm a bit confused.

I tested this on my Nexus 4 with Android 5.0 and Chrome 41.0.2272.96.

**Comment by IjzerenHein** [comment]
How does it compare to the stock famo.us scrollview? We've tested it on various Android devices, and albeit that performance varies per device and per chrome version, performance seems on par with the stock famo.us scrollview.

**Comment by ShawnOceanHu** [comment]
Hi I have just testd, the stock famo.us scrollview felt also bit laggy as the finger flings the view on the Nexus 4.

I have submitted an issue to famo.us: https://github.com/Famous/famous/issues/669

**Comment by ShawnOceanHu** [comment]
Hi, I'm closing this issue since this seems to be caused by the limitations of Android WebView, and Crosswalk might be the answer according to https://github.com/Famous/famous/issues/669, I will test this soon and will add a comment : )

**Comment by IjzerenHein** [comment]
Awesome :)
