### ISSUE TITLE
Manipulating sizes individually in famous-flex

### ISSUE THREAD

**Issue by sayawan** [IjzerenHein/famous-flex#85]
For example, in a List Layout how can I manipulate size of one surface on click . In a famous default scrollview we will do RenderNode > Modifier > Surface http://jsbin.com/naviy/1/edit?js,output

http://stackoverflow.com/a/27529200

**Comment by IjzerenHein** [comment]
Hi, you can use the following options for that:

```javascript
var scrollView = new FlexScrollView({
  layoutOptions: {
    itemSize: true // this causes the size from the renderable to be used (it calls getSize)
  }
  alwaysLayout: true // this ensures that the getSize function on the renderable is called every render-cycle
});
```

Also have a look at: #69

Let me know whether that solves the problem for you.
Cheers.

**Comment by sayawan** [comment]
Yes, thank you. Great! It solves my problem. Actually I found it yesterday just after writing this issue, I was curious if there is other way to do it in famous-flex.
