### ISSUE TITLE
Dropped in ScrollView, solved my problem.

### ISSUE THREAD

**Issue by markmarijnissen** [IjzerenHein/famous-flex#88]
Hi,

Just wanted to say thanks - the famo.us scrollview wasn't working properly, and because or the API is backwards compatible, I could just drop-in the FlexScrollView and my problems were solved :)

awesome

Mark

**Comment by sayawan** [comment]
Same here :+1: 
Thanks for awesome work :) I m visiting famous-flex documentation more frequently than famo.us one

**Comment by IjzerenHein** [comment]
Thanks guys, really appreciate it!
Glad you like it :)
