### ISSUE TITLE
Scrolling broken after transform 90 degrees

### ISSUE THREAD

**Issue by nicholasareed** [IjzerenHein/famous-flex#94]
I have a StateModifier with a transform like `Transform.rotateZ(-1 * Math.PI / 2)` as a parent of a FlexScrollView. The items are laid out correctly (appear vertical), but the scrolling only works left/right, not up/down as I would have hoped. 

Screenshot: https://www.dropbox.com/s/6r2bta7w207k99f/Screenshot%202015-04-27%2009.30.38.png?dl=0

Is there an easy solution to getting scrolling working in this fashion? Perhaps adding a parent/container flexscroll with alignment:1 and vertical scrolling would be a quick fix? 

Also, is there a solid base jsFiddle that includes famous-flex?

**Comment by IjzerenHein** [comment]
No, there's no way to fix that. Looking at the screenshot, I would solve it differently.
- Create a FlexScrollView with direction 1
- Rotate each individual surface

**Comment by nicholasareed** [comment]
There are a few reasons that enabling this rotated scrolling would be really helpful, mostly because the other way has the following problems: 

1) FlexScrollView is expecting dataSource items to be laid out vertically, but I need them to have an undefined height (or appear to, like the screenshot)  

2) I'm using `alignment:1`, which results in things appearing to come from the left side, but I'm forced to reverse() my dataSource every time in order to display the correct order of blocks from left-to-right. An option to set `reverse` on the FlexScrollView would be great (exists already?)  

3) there doesn't appear to be an easy way to start the list from the bottom/left. I tried a few origin/align pairs, but ended up being forced to do a goToLastPage() after it is loaded, which looks pretty ugly 

I've kinda got it working, but it requires a lot of static sizing and bad animations. If it is possible to get the rotated scrolling working, can you point me where I should start?

**Comment by IjzerenHein** [comment]
Hi Nick,

Sorry for not getting back sooner.
So, I still don't understand your use case and why you want to solve the things the way you want them to. Maybe I'm missing a piece of the puzzle, could be. So instead of posting what changes you need, could you post the end result that you want to achieve (a screenshot including the scroll direction will suffice), and I will try to find the best possible solution for it using the existing features in the FlexScrollView.

cheers
