### ISSUE TITLE
Remove has stopped working

### ISSUE THREAD

**Issue by ArjunRajJain** [IjzerenHein/famous-flex#95]
Getting the following error when I call remove(index) on a FlexScrollView 
![screen shot 2015-04-27 at 1 05 44 pm](https://cloud.githubusercontent.com/assets/2289559/7356610/29524178-ecde-11e4-81ed-d362a545f0cf.png)

**Comment by IjzerenHein** [comment]
Hi, and thank you very much for reporting this. This one seems to have slipped through the cracks.. I've just committed the fix onto the master. Tomorrow after I have done some more testing, I will release the fix into an official release.
Cheers

**Comment by IjzerenHein** [comment]
Hi, can I close this one?

**Comment by ArjunRajJain** [comment]
yep!

**Comment by IjzerenHein** [comment]
Awesome!
