### ISSUE TITLE
Howto remember position of FlexScrollView and go back to it without animation

### ISSUE THREAD

**Issue by rbabayoff** [IjzerenHein/famous-flex#98]
Hey, 

I posted this question in stackoverflow, but didn't get an answer, so trying here too. Hope it's OK.

Link to question:

http://stackoverflow.com/questions/29982163/howto-remember-position-of-flexscrollview-and-go-back-to-it-without-animation

**Comment by IjzerenHein** [comment]
Hmm that's weird, that should have just worked. At least it used to work.. What version are you using?

**Comment by IjzerenHein** [comment]
So basically, the FlexScrollView will remember the current scroll position, whether it is shown or not. Only if you manipulate it, like adding, removing, changing layout, scrolling to a page, etc... will it change the scroll position. Are you sure you are not removing all the content, and re-adding it?

**Comment by rbabayoff** [comment]
Hey, I'm using v0.3.0. Views are the same, they are not destroyed - they are only created once per route. But I use a RenderController to show and hide views, depending on route. Should I create a simple reproduction of bug or do you have enough info?

**Comment by IjzerenHein** [comment]
Could you share a demo online, so I can debug that?
